version: '3'
services:
  app-php:
    build:
      args:
        user: user
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: app_php
    container_name: app_php
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    depends_on:
      - app-db
      - app-nginx

    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./infra/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  app-nginx:
    image: nginx:alpine
    container_name: app_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./infra/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  app-db:
    image: mariadb:10.5.3
    container_name: app_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
      MYSQL_USER: 'user'
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    volumes:
      - app-data:/var/lib/mysql/
      - ./infra/mariadb/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    driver: local
